import { Poppins } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Footer from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";

export const senFont = localFont({
  src: "../fonts/Sen-VariableFont_wght.ttf",
})

const poppins = Poppins({
  weight: [ "100", "200", "400", "500", "600", "800" ]
});

export const metadata = {
  title: {
    default: "HeroKidz",
    template: "%s | HeroKidz"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
